name: Print Log

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  log-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello, GitHub Actions! This is a simple print statement."
